//! # Database Module (SQLite)
//! 
//! This module manages all local data persistence using SQLite.
//! It handles schema initialization, client records, prefix-to-client mapping,
//! and routing loop history from previous scans (used to compute diffs).

use rusqlite::{params, Connection, Result};

/// Represents a Client record in the database.
#[derive(Debug)]
pub struct Client {
    /// Unique identifier auto-generated by SQLite.
    pub id: i64,
    /// Unique name of the client (e.g., "Company").
    pub name: String,
    /// Email where loop reports will be sent.
    pub email: String,
    /// Corporate/Legal name used to customize the email alert body.
    pub corporate_name: String,
}

/// Initializes the SQLite database at the specified path and creates the required tables
/// if they do not exist. It also enables foreign key support.
pub fn init_db(db_path: &str) -> Result<Connection> {
    let conn = Connection::open(db_path)?;
    
    // Create clients table
    conn.execute(
        "CREATE TABLE IF NOT EXISTS clients (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT UNIQUE NOT NULL,
            email TEXT NOT NULL,
            description TEXT NOT NULL
        )",
        [],
    )?;
    
    // Create IP prefixes table (IPv4 and IPv6) associated with clients.
    // CASCADE ensures that deleting a client removes all associated prefixes.
    conn.execute(
        "CREATE TABLE IF NOT EXISTS prefixes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            client_id INTEGER NOT NULL,
            prefix TEXT UNIQUE NOT NULL,
            asn TEXT,
            FOREIGN KEY(client_id) REFERENCES clients(id) ON DELETE CASCADE
        )",
        [],
    )?;

    // Checks if the 'asn' column exists in the 'prefixes' table. If not, runs ALTER TABLE.
    let mut asn_exists = false;
    if let Ok(mut stmt) = conn.prepare("PRAGMA table_info(prefixes)") {
        if let Ok(mut rows) = stmt.query([]) {
            while let Ok(Some(row)) = rows.next() {
                let name: String = row.get(1)?;
                if name == "asn" {
                    asn_exists = true;
                    break;
                }
            }
        }
    }
    if !asn_exists {
        let _ = conn.execute("ALTER TABLE prefixes ADD COLUMN asn TEXT", []);
    }
    
    // Checks if the existing active_loops table is an older version (without target_ip in the primary key).
    // If it is, drops the table to recreate it with the correct composite primary key.
    let mut target_ip_in_pk = false;
    if let Ok(mut stmt) = conn.prepare("PRAGMA table_info(active_loops)") {
        if let Ok(mut rows) = stmt.query([]) {
            while let Ok(Some(row)) = rows.next() {
                let name: String = row.get(1)?;
                let pk: i32 = row.get(5)?;
                if name == "target_ip" && pk > 0 {
                    target_ip_in_pk = true;
                }
            }
        }
    }

    if !target_ip_in_pk {
        conn.execute("DROP TABLE IF EXISTS active_loops", [])?;
    }

    // Table to store the state of the last scan.
    // Used to compare the previous execution with the current one and compute diffs.
    // The primary key includes target_ip to support multiple loops within the same prefix.
    conn.execute(
        "CREATE TABLE IF NOT EXISTS active_loops (
            client_id INTEGER NOT NULL,
            prefix TEXT NOT NULL,
            target_ip TEXT NOT NULL,
            router_ip TEXT NOT NULL,
            PRIMARY KEY(client_id, prefix, target_ip),
            FOREIGN KEY(client_id) REFERENCES clients(id) ON DELETE CASCADE
        )",
        [],
    )?;
    
    // Enables foreign key constraints in SQLite
    conn.execute("PRAGMA foreign_keys = ON", [])?;
    
    Ok(conn)
}

/// Registers a new client in the clients table.
pub fn add_client(conn: &Connection, name: &str, email: &str, description: &str) -> Result<()> {
    conn.execute(
        "INSERT INTO clients (name, email, description) VALUES (?1, ?2, ?3)",
        params![name, email, description],
    )?;
    Ok(())
}

/// Updates the details of an existing client.
pub fn update_client(
    conn: &Connection,
    name: &str,
    new_name: Option<&str>,
    email: Option<&str>,
    description: Option<&str>,
) -> Result<usize> {
    let client = get_client_by_name(conn, name)?;
    match client {
        Some(c) => {
            let final_name = new_name.unwrap_or(&c.name);
            let final_email = email.unwrap_or(&c.email);
            let final_corporate_name = description.unwrap_or(&c.corporate_name);
            
            let count = conn.execute(
                "UPDATE clients SET name = ?1, email = ?2, description = ?3 WHERE id = ?4",
                params![final_name, final_email, final_corporate_name, c.id],
            )?;
            Ok(count)
        }
        None => Ok(0),
    }
}

/// Removes a client by name. Due to ON DELETE CASCADE,
/// all associated prefixes and loop histories are automatically deleted.
pub fn remove_client(conn: &Connection, name: &str) -> Result<usize> {
    conn.execute("DELETE FROM clients WHERE name = ?1", params![name])
}

/// Returns a list of all registered clients in the database.
pub fn list_clients(conn: &Connection) -> Result<Vec<Client>> {
    let mut stmt = conn.prepare("SELECT id, name, email, description FROM clients ORDER BY name")?;
    let client_iter = stmt.query_map([], |row| {
        Ok(Client {
            id: row.get(0)?,
            name: row.get(1)?,
            email: row.get(2)?,
            corporate_name: row.get(3)?,
        })
    })?;

    let mut clients = Vec::new();
    for client in client_iter {
        clients.push(client?);
    }
    Ok(clients)
}

/// Finds a client by its unique name. Returns `None` if not found.
pub fn get_client_by_name(conn: &Connection, name: &str) -> Result<Option<Client>> {
    let mut stmt = conn.prepare("SELECT id, name, email, description FROM clients WHERE name = ?1")?;
    let mut rows = stmt.query(params![name])?;
    if let Some(row) = rows.next()? {
        Ok(Some(Client {
            id: row.get(0)?,
            name: row.get(1)?,
            email: row.get(2)?,
            corporate_name: row.get(3)?,
        }))
    } else {
        Ok(None)
    }
}

/// Associates a CIDR prefix (IPv4 or IPv6) with an existing client and an optional ASN.
pub fn add_prefix(conn: &Connection, client_name: &str, prefix: &str, asn: Option<&str>) -> Result<()> {
    let client = get_client_by_name(conn, client_name)?;
    match client {
        Some(c) => {
            conn.execute(
                "INSERT INTO prefixes (client_id, prefix, asn) VALUES (?1, ?2, ?3)",
                params![c.id, prefix, asn],
            )?;
            Ok(())
        }
        None => Err(rusqlite::Error::QueryReturnedNoRows),
    }
}

/// Removes a specific IP prefix from the database.
pub fn remove_prefix(conn: &Connection, prefix: &str) -> Result<usize> {
    conn.execute("DELETE FROM prefixes WHERE prefix = ?1", params![prefix])
}

/// Helper structure containing prefix details associated with its client and ASN.
pub struct PrefixInfo {
    pub prefix: String,
    pub client_name: String,
    pub asn: Option<String>,
}

/// Returns a list of prefixes, optionally filtered by client name.
pub fn list_prefixes(conn: &Connection, client_name_filter: Option<&str>) -> Result<Vec<PrefixInfo>> {
    let mut query = String::from(
        "SELECT p.prefix, c.name, p.asn FROM prefixes p 
         JOIN clients c ON p.client_id = c.id "
    );
    
    if client_name_filter.is_some() {
        query.push_str("WHERE c.name = ?1 ");
    }
    
    query.push_str("ORDER BY c.name, p.prefix");
    
    let mut stmt = conn.prepare(&query)?;
    
    let mapper = |row: &rusqlite::Row| {
        Ok(PrefixInfo {
            prefix: row.get(0)?,
            client_name: row.get(1)?,
            asn: row.get(2)?,
        })
    };

    let prefix_iter = if let Some(filter) = client_name_filter {
        stmt.query_map(params![filter], mapper)?
    } else {
        stmt.query_map([], mapper)?
    };

    let mut prefixes = Vec::new();
    for prefix in prefix_iter {
        prefixes.push(prefix?);
    }
    Ok(prefixes)
}

/// Structure to represent a prefix associated with a client and its ASN.
#[derive(Debug, Clone)]
pub struct ClientPrefix {
    pub prefix: String,
    pub asn: Option<String>,
}

/// Returns all prefixes associated with a client ID, including their ASNs.
pub fn get_prefixes_for_client(conn: &Connection, client_id: i64) -> Result<Vec<ClientPrefix>> {
    let mut stmt = conn.prepare("SELECT prefix, asn FROM prefixes WHERE client_id = ?1")?;
    let prefix_iter = stmt.query_map(params![client_id], |row| {
        Ok(ClientPrefix {
            prefix: row.get(0)?,
            asn: row.get(1)?,
        })
    })?;
    
    let mut prefixes = Vec::new();
    for prefix in prefix_iter {
        prefixes.push(prefix?);
    }
    Ok(prefixes)
}

/// Structure to store historical routing loop details.
pub struct SavedLoop {
    /// The CIDR prefix exhibiting a routing loop.
    pub prefix: String,
    /// The target IP that was tested.
    pub target_ip: String,
    /// The router IP that responded with "Time Exceeded" (loop source).
    pub router_ip: String,
}

/// Retrieves loops that were active in the client's last scan.
pub fn get_active_loops(conn: &Connection, client_id: i64) -> Result<Vec<SavedLoop>> {
    let mut stmt = conn.prepare("SELECT prefix, target_ip, router_ip FROM active_loops WHERE client_id = ?1")?;
    let rows_iter = stmt.query_map(params![client_id], |row| {
        Ok(SavedLoop {
            prefix: row.get(0)?,
            target_ip: row.get(1)?,
            router_ip: row.get(2)?,
        })
    })?;

    let mut loops = Vec::new();
    for item in rows_iter {
        loops.push(item?);
    }
    Ok(loops)
}

/// Updates active loops history for a client in a transaction.
/// Deletes previous loops for the client and inserts the newly detected ones.
pub fn set_active_loops(conn: &mut Connection, client_id: i64, loops: &[SavedLoop]) -> Result<()> {
    let tx = conn.transaction()?;
    tx.execute("DELETE FROM active_loops WHERE client_id = ?1", params![client_id])?;
    for l in loops {
        tx.execute(
            "INSERT INTO active_loops (client_id, prefix, target_ip, router_ip) VALUES (?1, ?2, ?3, ?4)",
            params![client_id, l.prefix, l.target_ip, l.router_ip],
        )?;
    }
    tx.commit()?;
    Ok(())
}
